{"name": "反向用例: raise TypeError", "status": "passed", "attachments": [{"name": "log", "source": "a52a5c46-58fb-4f5d-ae51-37332fab790e-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "a", "value": "1"}, {"name": "b", "value": "'2'"}, {"name": "error_type", "value": "'TypeError'"}], "start": 1624194308151, "stop": 1624194308151, "uuid": "f25b4d02-63dd-46d6-9041-e77b14d56284", "historyId": "a6ee0ce94658cc2088a0ab0fdd923302", "testCaseId": "1b5aab2181c21923f6bd8223ee598e23", "fullName": "Test_2021_06_17.test_cal.test_cal.TestAddDivision#test_add_fail", "labels": [{"name": "story", "value": "测试加法"}, {"name": "feature", "value": "测试计算器"}, {"name": "parentSuite", "value": "Test_2021_06_17.test_cal"}, {"name": "suite", "value": "test_cal"}, {"name": "subSuite", "value": "TestAddDivision"}, {"name": "host", "value": "192.168.8.102"}, {"name": "thread", "value": "56258-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "Test_2021_06_17.test_cal.test_cal"}]}