{"name": "反向用例: raise TypeError", "status": "passed", "attachments": [{"name": "log", "source": "11002475-d2a3-403d-ad7b-2beb85632e8e-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "a", "value": "1"}, {"name": "b", "value": "'2'"}, {"name": "error_type", "value": "'TypeError'"}], "start": 1624194308168, "stop": 1624194308168, "uuid": "62c361ce-88c6-477f-97a0-182c9e335db7", "historyId": "9a9d7bb966ac9488ed532efc60080fe4", "testCaseId": "f221dbe9823e9f06e0f386ff52a476fb", "fullName": "Test_2021_06_17.test_cal.test_cal.TestAddDivision#test_division_success", "labels": [{"name": "story", "value": "测试除法"}, {"name": "feature", "value": "测试计算器"}, {"name": "parentSuite", "value": "Test_2021_06_17.test_cal"}, {"name": "suite", "value": "test_cal"}, {"name": "subSuite", "value": "TestAddDivision"}, {"name": "host", "value": "192.168.8.102"}, {"name": "thread", "value": "56258-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "Test_2021_06_17.test_cal.test_cal"}]}