{"name": "反向用例: raise TypeError", "status": "passed", "attachments": [{"name": "log", "source": "18d029b6-c112-481d-a896-34f7439db220-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "a", "value": "1"}, {"name": "b", "value": "'2'"}, {"name": "error_type", "value": "'TypeError'"}], "start": 1624194207756, "stop": 1624194207756, "uuid": "7d38a15c-2e8c-4bc9-88a5-ff54c0eb7a25", "historyId": "4057b389ada215182f9cc8de0d07e30b", "testCaseId": "1b5aab2181c21923f6bd8223ee598e23", "fullName": "Test_2021_06_17.test_cal.test_cal.TestAddDivision#test_add_fail", "labels": [{"name": "story", "value": "测试加法"}, {"name": "feature", "value": "测试计算器"}, {"name": "parentSuite", "value": "Test_2021_06_17.test_cal"}, {"name": "suite", "value": "test_cal"}, {"name": "subSuite", "value": "TestAddDivision"}, {"name": "host", "value": "192.168.8.102"}, {"name": "thread", "value": "56187-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "Test_2021_06_17.test_cal.test_cal"}]}